# Generated by Django 4.2.1 on 2023-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_event_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
    ]
